project:
  type: book
  output-dir: docs

execute: 
  freeze: auto

jupyter: python3

book:
#  navbar:
#    search: true 
  title: "AutoDiff"
  subtitle: "Eine Einführung in algorithmisches Differenzieren"
  author: "Michael Brand"
  date: "10/19/2022"
  favicon: mycover.png      
  sidebar: 
    logo: mycover.png
  page-navigation: true
  search: true
#  cookie-consent: express
  downloads: [pdf]
#  sharing: [twitter, facebook, instagram]
  chapters:
    - index.qmd
    - intro.qmd
    - notAD.qmd
    - ADOneDimManually.qmd
    - HigherDimFunctions.qmd
    - aad.qmd
    - references.qmd
    

bibliography: references.bib

format:
  html:
    theme: cosmo
    code-copy: hover
    code-fold: true
    html-math-method: mathjax
    lang: de
    number-depth: 3
    toc: true
    toc-depth: 3
    reference-location: margin
  pdf:
    documentclass: scrreprt
    papersize: A4
    lang: de
    geometry: 
      - top = 30mm
      - left = 20mm
      - bottom = 60mm
      - right = 20mm
      - heightrounded
    number-sections: true
    number-depth: 2
#    pdf-engine: latexmk
    latex-tinytex: true
    toc: true
    toc-depth: 3
    colorlinks: true
    reference-location: section
    cap-location: bottom
    fig-pos: H
    output-file: AutoDiff.pdf
    latex-auto-mk: true
    latex-auto-install: true
#    include-in-header: 
#      text: |
#        \usepackage{amssymb,amsmath,amsthm, amsfonts}